# Generated by Django 3.0.5 on 2020-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20200420_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='days_to_harvest',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
